#!/bin/bash
COUNTER=0
touch photos
# for i in $(ls ./thumb); do
#   let COUNTER=COUNTER+1
#   # mv ./thumb/$i ./thumb/$COUNTER.jpg
#   echo $i $COUNTER
# done

# IFS is file separator which is a space char by default
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# set folder to iterate
FOLDER=./large/
FILES=$FOLDER*
for f in $FILES
do
  # echo "$f"
  let COUNTER=COUNTER+1
  NEWFILE=$COUNTER.jpg
  mv $f $FOLDER$COUNTER.jpg
  echo "{url: \"/images/wedphotos/large/$NEWFILE\",categoryId:1,id:$COUNTER,thumbUrl: \"/images/wedphotos/thumb/$NEWFILE\"}," >> photos

done
# restore $IFS
IFS=$SAVEIFS
echo ""
echo $COUNTER
