#!/bin/bash
COUNTER=0
# for i in $(ls ./thumb); do
#   let COUNTER=COUNTER+1
#   # mv ./thumb/$i ./thumb/$COUNTER.jpg
#   echo $i $COUNTER
# done

# IFS is file separator which is a space char by default
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
# set folder to iterate
FILES=./large/*
for f in $FILES
do
  # echo "$f"
  let COUNTER=COUNTER+1
  mv $f ./large/$COUNTER.jpg
done
# restore $IFS
IFS=$SAVEIFS
echo ""
echo $COUNTER
